name: Deploy to Github Page
on:
  push:
    branches:
      - himal

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1


      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
            node-version: 'node'

      - name: Install dependencies
        run: npm install


      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SEP6_TOKEN }}
          publish_dir: ./build

